.\" Copyright (C) 2001 Joachim Wieland <joe@mcknight.de>
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 2 of the License, or (at your
.\" option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 59 Temple Place - Suite 330, Boston, MA 02111, USA.
.\"
.TH JFTPGW 1 "18 November 2001" "jftpgw" "User Manuals"
.SH NAME
jftpgw \- an FTP application level proxy/gateway
.SH SYNOPSIS
.B jftpgw
[OPTION]...
.SH DESCRIPTION
.PP
This manual page documents the program
.B jftpgw
which is an FTP proxy/gateway that uses the FTP protocol (unlike those FTP
proxies that fetch via FTP but provide the file via HTTP). You can use it to
make servers behind a firewall/NAT server (masquerading server) accessible
or to allow users behind such solutions to transfer files to and from the
outside of the LAN.
.SH OPTIONS
.TP
.I "\-e, \-\-encrypt"
Start the small, built-in password creation. jftpgw will read your input
password, output a crypt()ed version of this password and exit.
.TP
.I "\-f, \-\-configfile FILE"
Read FILE instead of the default configfile (instead of the built-in
location)
.TP
.I "\-h, \-\-help"
Display a short help text.
.TP
.I "\-i, \-\-inetd"
Tell jftpgw that it is run from inetd. In this case it will not try to
become a daemon.
.TP
.I "\-s, \-\-single"
Run only a single thread of jftpgw (you won't need this option in the normal
use. It's nice for debugging, to trace the program or execute it within a
debugger).
.TP
.I "\-t, \-\-tcpwrap"
Use libwrap for access control. This will disable the "normal" access
control via the "access allow|deny" directives in the configuration file.
Make sure you have libwrap support compiled in (check with --version)
.TP
.I "\-V, \-v, \-\-version"
Display the version number and exit.
.SH NOTES
.PP
Please note that the 0.13.x version is the first one that has a different
configuration than the versions released previously.  The new configuration
has a completely different (more flexible) configuration system and the
internal structure changed a lot.
.SH AVAILABILITY
.PP
The latest release is available on the jftpgw homepage.
.PP
Primary site: http://www.mcknight.de/jftpgw/
.SH "SEE ALSO"
.PP
Further information can be found in the
.I jftpgw.conf
file. The config file contains a description and some examples for every
option.
.TP
.I http://www.mcknight.de/jftpgw/
contains further information on how to configure the program for special
purposes and a list of all configuration options.
.SH AUTHORS
.PP
Joachim Wieland <joe@mcknight.de> is the original author and current
maintainer of jftpgw.

